### PR TITLE
Create youtube.html

### PR DESCRIPTION
**Pull request by hzik**
# kc_youtube

This KC custom element allows you to add various types of youtube video url, it extracts the video id for your apps and shows the video.

You can test it by configuring https://amend.cz/youtube/youtube.html url for your custom element.

screenshot

You can specify the Parameters {JSON} part of the configuration to configure the default state or a lable.
Possible configurations:

{
    "width": 800,
    "height": 600
}

screenshot

### CODE REVIEW

**Comment by Simply007** [comment]
Hi @hzik,

please adjust the pull request description.

Could you please provide the [documentation markdown file](https://github.com/Kentico/custom-element-samples#custom-elements-contest-2019) with the description of how to use the element.

I have also noticed that the youtube selector is also being implemented by @ileshmistry (#2). Let's see who will have a better solution!

Thank Honza for the contribution!

**Comment by hzik** [comment]
# kc_youtube

This KC custom element allows you to add various types of youtube video url, it extracts the video id for your apps and shows the video.

You can test it by configuring https://amend.cz/youtube/youtube.html url for your custom element.

screenshot

You can specify the Parameters {JSON} part of the configuration to configure the default state or a lable.
Possible configurations:

{
    "width": 800,
    "height": 600
}

screenshot

**Comment by Simply007** [comment]
Great thanks.

I have moved the content with your description to the pull request description.

There is only thing left.
* Submit a new readme markdown file in your custom element folder with the same description (and the link to the source repository) as it is in pull request and I am happy to merge it!

**Comment by Simply007** [comment]
Great @hzik,

I have just renamed the custom element to be more specific and to have the folder names consistent!

Please accept my invitation to the Kentico Github organization so that I am able to assign you the pull request!

Thanks!

**Pull request merged**
