### PR TITLE
Flickr image picker 3.0

### PR DESCRIPTION
**Pull request by maartenvdh**
### Motivation

New custom element similar to the Flickr image picker only in this case with the Bing API.

Which issue does this fix? Fixes #`issue number`

If no issue exists, what is the fix or new feature? Were there any reasons to fix/implement things that are not obvious?

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [x] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

If you want to use the Bing image picker in your project in Kentico Cloud, follow these steps:

* In Kentico Cloud open the Content types tab
* Create or edit a content model to which you want to add the Bing image picker
* Add the **Custom element** content element
* Configure the content element
* Use the following URL as Hosted code URL (HTTPS): https://kentico.github.io/custom-element-samples/BingImagePicker/bingimage-input-component.html
* Get API key for Flickr:  https://www.flickr.com/services/developer/api/
* Provide JSON parameters for the custom element to configure the API Key:

```json
{
    "apikey": "[YOUR API KEY]"
}
```

### CODE REVIEW

**Comment by maartenvdh** [comment]
> * It would be great to have a sample output format in the description so that user knows what to expect in delivery API

@Simply007 thanks for you're usefull comments, I am busy to add them to my solution. I am only curious what you mean with "It would be great to have a sample output format in the description so that user knows what to expect in delivery API". Can you maybe give a example?

**Comment by Simply007** [comment]
Sure, something like [this](https://github.com/Kentico/custom-element-samples/tree/master/YouTube#example-output).

Basically the example output format that user gets in delivery API when he requests the data containing Flickr custom element.

**Comment by maartenvdh** [comment]
> Sure, something like [this](https://github.com/Kentico/custom-element-samples/tree/master/YouTube#example-output).
> 
> Basically the example output format that user gets in delivery API when he requests the data containing Flickr custom element.

@Simply007 ok now I understand what you are saying. I am not storing the whole element with all values. It only stores the url of the image. Do you want me to change that?

**Comment by Simply007** [comment]
@maartenvdh

It is completely fine, how you store the data. 

To give you a bit of the context by this requirement: Gif/image is readme is enough to provide more bussiness oriented users the high level picture about the custom element. For the developers who are considering using the custom element as an inspiration for production custom element, it is important what data (incl. the format) are stored primarily to decide whether the custom element suits their use-case.

**Comment by maartenvdh** [comment]
> Hello @maartenvdh,
> 
> thanks for the contribution(s).
> 
> I have gone through the code and I have a couple of notes:
> 
> * It would be great to have a sample output format in the description so that user knows what to expect in delivery API
> * From a user point a view, it would be very beneficial to have some notification if an error happened. The most common could be that no configuration file is provided, the invalid format of the configuration JSON (or even error in API key provided), error in network communication
> * The showcase gif looks outdated - there is no clear button
> * I have tested the custom element and after generating the API key I am not able to see the images:
>   image
>   
>   * The urls looks like:
>     
>     * https://farm66.static.flickr.com/65535/33738242248_17e0a46192_m.jpg
>     * https://farm66.static.flickr.com/65535/33738228608_5093dc0b17_m.jpg
> 
> I would also delete the `.gitignore`, but it is just a minority.
> 
> Could you also incorporate the notes in the #46 and #48?

@Simply007 implemented all comments in all three custom elements (#47 #46 & #48). When there are questions or suggestions please let me known!

**Comment by Simply007** [comment]
@maartenvdh thank!

I will review the changes ASAP and then wait for the decision on how to handle sensitive API key storage (#32).

**Comment by Simply007** [comment]
I have gone through the code, and I tried to use the styles that we are using in the Kentico Cloud UI for the disabling the elements instead of the overlay:
* https://kentico.github.io/custom-element-samples/shared/examples.html

If you find that approach better, approve the [pull request](https://github.com/maartenvdh/custom-element-samples/pull/2) and it will automatically propagate to this one and make the changes in Giphy #48 and Bing #44 selector.

It is a great showcase - thanks for that!

**Pull request merged**
