### PR TITLE
Create switch.html

### PR DESCRIPTION
**Pull request by hzik**
### Motivation

# Switch

This KC custom element is just a simple switch -> on/off

You can test it by configuring https://amend.cz/inputs/switch.html url for your custom element.

screenshot

You can specify the Parameters {JSON} part of the configuration to configure the default state or a lable.
Possible configurations:

(empty)

{ "default": true }

{
    "label": "Confirmed"
}

{
    "default": true,
    "label": "Accepted"
}

### CODE REVIEW

**Comment by Simply007** [comment]
Could you add the `Readme.md` with the description to the pull request as it was done in this pull request: #21 
* Please don't forget to add the URL to the element when the pull request is approved

**Comment by Simply007** [comment]
Isn't it more of a toggle button than switch?

**Comment by hzik** [comment]
It's inspired by Kentico's styling guide for the Switch control -> https://github.com/Kentico/custom-element-samples/blob/master/shared/examples.html

**Comment by Simply007** [comment]
I have done some structure polishing.

Tested manually.

Thanks @hzik!

**Pull request merged**
