### PR TITLE
Add Google places search element

### PR DESCRIPTION
**Pull request by ChristopherJennings**
### Motivation

Implements #14 

### Checklist

- [x] Code follows coding conventions held in this repo
- [ ] Automated tests have been added
- [ ] Tests are passing
- [x] Docs have been updated (if applicable)
- [x] Temporary settings (e.g. variables used during development and testing) have been reverted to defaults

### How to test

Follow instructions in readme.

### CODE REVIEW

**Comment by ChristopherJennings** [comment]
1. I thought I had address the null value save, but I must have missed that for the clear button. I'll make sure that's addressed. 
1. I'll make sure the font is included/linked appropriately.
1. I'll add an error message for missing/invalid configuration
1. There is a [source repo](https://github.com/ChristopherJennings/google-places-search-element), and I'll link that up inthe readme. 
1. I specifically disabled scrolling/clicking for this iteration. I see that as a VNext feature.

**Comment by ChristopherJennings** [comment]
One more note on the font, I used the devkit to build/test this. AM I missing some option or instruction to make that get included correctly in the build?

**Comment by Simply007** [comment]
[Step no. 7](https://github.com/kentico/custom-element-devkit#adding-custom-elements) does not work?

**Comment by ChristopherJennings** [comment]
That's how I did it from the start. The woff appears to get added to the root of the `built` folder rather. than be included in the element's folder. [repo](https://github.com/ChristopherJennings/google-places-search-element)

**Comment by ChristopherJennings** [comment]
@Simply007 I've fixed the issues except the font file. Should I open an issue there for resolution and wait for the fix or should I manually fix it in this PR for now?

**Comment by Simply007** [comment]
@ChristopherJennings - Please submit the issue to the repository.

**Comment by ChristopherJennings** [comment]
Looks like [it's already been reported](https://github.com/Kentico/custom-element-devkit/issues/6). ShoulId just manually correct this in the PR for now?

**Comment by Simply007** [comment]
Yes please @ChristopherJennings

**Comment by ChristopherJennings** [comment]
Manually corrected font URL and included file.

**Comment by Simply007** [comment]
It is neccesarry to fix the font path in `index.html` file:
from `/kentico-icons-v1.6.0.woff` to `./kentico-icons-v1.6.0.woff`

and I think the `bundle.css` and `bundle .js` are not necessary for the pull request since its content is already included and inlined in the `index.html` file.

**Comment by ChristopherJennings** [comment]
I completely missed that... That's the problem with automated tools (especially when they're broken). 

Should be set for real this time.

**Comment by Simply007** [comment]
Thanks. 

I will just adjust the link to the configuration to be opened in a new tab - because it can't be loaded in the frame (GitHub return `X-Frame-Options: deny` HTTP header).

**Comment by Simply007** [comment]
Link adjustments: https://github.com/Kentico/custom-element-samples/commit/83afbc9f904eeb54bed5d98a18ba67aab5390d9a

**Pull request merged**
